### ISSUE TITLE
本地启动异常

### ISSUE THREAD

**Issue by ooocici** [Java-S12138/frank#95]
Node 版本: `v18.0.0`
Npm  版本: `8.18.0`
OS     版本: `MacOS Catelina 10.15.7`

操作步骤：
终端执行 `yarn electron:serve` 命令，显示Compiled successfully信息，程序打印错误日志并退出。
错误日志如下：
```shell
Bundling main process...node:internal/crypto/hash:67
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (/Users/a/Documents/b/frank/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/Users/a/Documents/b/frank/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/Users/a/Documents/b/frank/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/NormalModule.js:471:10)
    at /Users/a/Documents/b/frank/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/NormalModule.js:503:5
    at /Users/a/Documents/b/frank/node_modules/vue-cli-plugin-electron-builder/node_modules/webpack/lib/NormalModule.js:358:12
    at /Users/a/Documents/b/frank/node_modules/vue-cli-plugin-electron-builder/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/Users/a/Documents/b/frank/node_modules/vue-cli-plugin-electron-builder/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/Users/a/Documents/b/frank/node_modules/vue-cli-plugin-electron-builder/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

**Comment by Java-S12138** [comment]
mac os   , 不能玩英雄联盟吧

**Comment by ooocici** [comment]
主要是学习☺️，请问一下作者此项目开发环境有版本要求吗？

**Comment by Java-S12138** [comment]
没有版本要求, 主要是我没在mac上面跑过, 所以也不太清楚

**Comment by ooocici** [comment]
作者你好，上述问题因node版本过高导致。
目前我已经切换为16.14.2 LTS 版本，可以正常运行，不过在窗体内提示”欢迎使用bigdata-macroeconomics后台管理框架，当前版本：v1.1.0，请通过前端地址访问。“。 我应该如何更改，让其显示正确的页面？
谢谢。

**Comment by ooocici** [comment]
经过确认，上述问题原因是Node版本过高， 切换为v16.x就能正常运行。
谢谢作者。
